name: Create zip file for download

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 11 * *"  # Run the workflow on the 1st and 15th day of each month
permissions:
  contents: write
  pages: write
  id-token: write
  issues: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  reactome:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps: 
    # step 1: connect to current repository
    - name: Checkout repository
      uses: actions/checkout@v4
      # step 2: download the recent data 
    # Runs a single command using the runners shell
    - name: zip files in repo
      run: |
        ls
        cd ~/wp
        zip -r wikipathways-20241110-rdf-reactome.zip ~/download
